version: '3'
services:
  api:
    build:
      context: ./backend
    networks:
      - socket-net
    environment:
      PORT: 80
    ports:
      - "8081:80"
  socket:
    build: 
      context: ./socketio
    environment:
      PORT: 80
      API_HOST: http://api
    networks:
      - socket-net
    ports:
      - "8082:80"

networks:
  socket-net:
